# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: papapool

variables:
  TF_VERSION: '1.5.7'

steps:

- task: UseTerraform@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: $(TF_VERSION)

- task: AzureCLI@2
  displayName: 'Login to Azure'
  inputs:
    azureSubscription: 'my-azure-connection'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show

- script: |
    terraform init
  displayName: 'Terraform Init'
  workingDirectory: $(Build.SourcesDirectory)

- script: |
    terraform plan
  displayName: 'Terraform Plan'
  workingDirectory: $(Build.SourcesDirectory)

- script: |
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
  workingDirectory: $(Build.SourcesDirectory)
